"""rename document_status to status and update status values

Revision ID: f43ea5dfa431
Revises: 8b1d6d216929
Create Date: 2025-09-17 11:18:33.937117

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mssql

# revision identifiers, used by Alembic.
revision = 'f43ea5dfa431'
down_revision = '8b1d6d216929'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('additional_documents', 'invoice_id',
               existing_type=sa.INTEGER(),
               comment='Reference to the parent invoice',
               existing_nullable=False)
    op.alter_column('additional_documents', 'document_type',
               existing_type=sa.NVARCHAR(length=10, collation='SQL_Latin1_General_CP1_CI_AS'),
               nullable=False,
               comment="Document type code (e.g., 'I-11' for Invoice, 'I-12' for Credit Note)")
    op.alter_column('additional_documents', 'document_number',
               existing_type=sa.VARCHAR(length=100, collation='SQL_Latin1_General_CP1_CI_AS'),
               server_default=None,
               existing_comment='Document number or identifier',
               existing_nullable=False)
    op.alter_column('additional_documents', 'document_date',
               existing_type=sa.DATE(),
               comment='Document date',
               existing_nullable=True)
    op.alter_column('additional_documents', 'description',
               existing_type=sa.NVARCHAR(length=500, collation='SQL_Latin1_General_CP1_CI_AS'),
               comment='Document description',
               existing_nullable=True)
    op.alter_column('additional_documents', 'created_at',
               existing_type=sa.DATETIME(),
               server_default=None,
               existing_nullable=False)
    op.create_index('idx_document_type', 'additional_documents', ['invoice_id', 'document_type'], unique=False)
    op.create_table_comment(
        'additional_documents',
        'Additional documents related to invoices',
        existing_comment=None,
        schema=None
    )
    op.drop_column('additional_documents', 'document_name')
    op.drop_column('additional_documents', 'document_id')
    op.drop_column('additional_documents', 'updated_at')
    op.drop_column('additional_documents', 'file_path')
    op.alter_column('companies', 'identifier',
               existing_type=sa.NVARCHAR(length=50, collation='SQL_Latin1_General_CP1_CI_AS'),
               comment='Unique company identifier (I-01 for TEIF)',
               existing_nullable=False)
    op.alter_column('companies', 'name',
               existing_type=sa.NVARCHAR(length=255, collation='SQL_Latin1_General_CP1_CI_AS'),
               comment='Company name (PartnerName in TEIF)',
               existing_nullable=False)
    op.alter_column('companies', 'vat_number',
               existing_type=sa.NVARCHAR(length=50, collation='SQL_Latin1_General_CP1_CI_AS'),
               comment='VAT registration number (I-1602 in TEIF)',
               existing_nullable=False)
    op.alter_column('companies', 'tax_id',
               existing_type=sa.NVARCHAR(length=50, collation='SQL_Latin1_General_CP1_CI_AS'),
               comment='Tax identification number (I-01 in TEIF)',
               existing_nullable=True)
    op.alter_column('companies', 'commercial_register',
               existing_type=sa.NVARCHAR(length=50, collation='SQL_Latin1_General_CP1_CI_AS'),
               comment='Commercial register number (I-815 in TEIF)',
               existing_nullable=True)
    op.alter_column('companies', 'address_street',
               existing_type=sa.NVARCHAR(length=500, collation='SQL_Latin1_General_CP1_CI_AS'),
               comment='Street address (Street in TEIF)',
               existing_nullable=True)
    op.alter_column('companies', 'address_city',
               existing_type=sa.NVARCHAR(length=100, collation='SQL_Latin1_General_CP1_CI_AS'),
               comment='City name (CityName in TEIF)',
               existing_nullable=True)
    op.alter_column('companies', 'address_postal_code',
               existing_type=sa.NVARCHAR(length=20, collation='SQL_Latin1_General_CP1_CI_AS'),
               comment='Postal/ZIP code (PostalCode in TEIF)',
               existing_nullable=True)
    op.alter_column('companies', 'address_country_code',
               existing_type=sa.NVARCHAR(length=3, collation='SQL_Latin1_General_CP1_CI_AS'),
               server_default=None,
               type_=sa.String(length=2),
               nullable=False,
               comment='ISO 3166-1 alpha-2 country code (Country in TEIF)')
    op.alter_column('companies', 'address_language',
               existing_type=sa.NVARCHAR(length=2, collation='SQL_Latin1_General_CP1_CI_AS'),
               server_default=None,
               nullable=False,
               comment='Language code for address (lang attribute in TEIF)')
    op.alter_column('companies', 'phone',
               existing_type=sa.NVARCHAR(length=50, collation='SQL_Latin1_General_CP1_CI_AS'),
               comment='Primary phone number (I-101 in TEIF)',
               existing_nullable=True)
    op.alter_column('companies', 'email',
               existing_type=sa.NVARCHAR(length=255, collation='SQL_Latin1_General_CP1_CI_AS'),
               comment='Primary email address (I-102 in TEIF)',
               existing_nullable=True)
    op.alter_column('companies', 'fax',
               existing_type=sa.NVARCHAR(length=50, collation='SQL_Latin1_General_CP1_CI_AS'),
               comment='Fax number (I-118 in TEIF)',
               existing_nullable=True)
    op.alter_column('companies', 'website',
               existing_type=sa.NVARCHAR(length=255, collation='SQL_Latin1_General_CP1_CI_AS'),
               comment='Company website URL (I-104 in TEIF)',
               existing_nullable=True)
    op.alter_column('companies', 'additional_info',
               existing_type=sa.VARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'),
               comment='Additional TEIF-specific information in JSON format',
               existing_comment='Additional company information in JSON format',
               existing_nullable=True)
    op.alter_column('companies', 'updated_at',
               existing_type=sa.DATETIME(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('companies', 'created_at',
               existing_type=mssql.DATETIME2(),
               server_default=None,
               type_=sa.DateTime(),
               nullable=False)
    op.drop_index(op.f('IX_companies_identifier'), table_name='companies')
    op.drop_index(op.f('IX_companies_vat_number'), table_name='companies')
    op.create_index('idx_company_commercial_register', 'companies', ['commercial_register'], unique=False)
    op.create_index('idx_company_identifier', 'companies', ['identifier'], unique=False)
    op.create_index('idx_company_name_city', 'companies', ['name', 'address_city'], unique=False)
    op.create_index('idx_company_tax_id', 'companies', ['tax_id'], unique=False)
    op.create_index('idx_company_vat', 'companies', ['vat_number'], unique=False)
    op.create_index(op.f('ix_companies_identifier'), 'companies', ['identifier'], unique=True)
    op.create_index(op.f('ix_companies_vat_number'), 'companies', ['vat_number'], unique=False)
    op.create_table_comment(
        'companies',
        'Companies and organizations that are suppliers or customers in the system',
        existing_comment=None,
        schema=None
    )
    op.alter_column('company_contacts', 'function_code',
               existing_type=sa.NVARCHAR(length=10, collation='SQL_Latin1_General_CP1_CI_AS'),
               comment="Contact function code (e.g., 'BU' for buyer, 'SU' for supplier)",
               existing_nullable=True)
    op.alter_column('company_contacts', 'contact_name',
               existing_type=sa.NVARCHAR(length=255, collation='SQL_Latin1_General_CP1_CI_AS'),
               comment='Full name of the contact person',
               existing_nullable=True)
    op.alter_column('company_contacts', 'contact_identifier',
               existing_type=sa.NVARCHAR(length=50, collation='SQL_Latin1_General_CP1_CI_AS'),
               comment='Unique identifier for the contact',
               existing_nullable=True)
    op.alter_column('company_contacts', 'created_at',
               existing_type=mssql.DATETIME2(),
               server_default=None,
               type_=sa.DateTime(),
               nullable=False)
    op.alter_column('company_references', 'reference_type',
               existing_type=sa.NVARCHAR(length=10, collation='SQL_Latin1_General_CP1_CI_AS'),
               comment="Reference type (e.g., 'VA' for VAT, 'FC' for Fiscal Code)",
               existing_nullable=False)
    op.alter_column('company_references', 'reference_value',
               existing_type=sa.NVARCHAR(length=100, collation='SQL_Latin1_General_CP1_CI_AS'),
               comment='The reference value',
               existing_nullable=False)
    op.alter_column('company_references', 'description',
               existing_type=sa.NVARCHAR(length=255, collation='SQL_Latin1_General_CP1_CI_AS'),
               comment='Optional description of the reference',
               existing_nullable=True)
    op.alter_column('company_references', 'created_at',
               existing_type=mssql.DATETIME2(),
               server_default=None,
               type_=sa.DateTime(),
               nullable=False)
    op.alter_column('contact_communications', 'communication_type',
               existing_type=sa.NVARCHAR(length=10, collation='SQL_Latin1_General_CP1_CI_AS'),
               comment="Type of communication (e.g., 'TE' for telephone, 'EM' for email)",
               existing_nullable=False)
    op.alter_column('contact_communications', 'communication_value',
               existing_type=sa.NVARCHAR(length=255, collation='SQL_Latin1_General_CP1_CI_AS'),
               comment='The communication value (e.g., phone number, email)',
               existing_nullable=False)
    op.alter_column('contact_communications', 'created_at',
               existing_type=mssql.DATETIME2(),
               server_default=None,
               type_=sa.DateTime(),
               nullable=False)
    op.add_column('generated_xml_files', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('generated_xml_files', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.alter_column('generated_xml_files', 'invoice_id',
               existing_type=sa.INTEGER(),
               comment='Reference to the source invoice',
               existing_nullable=False)
    op.alter_column('generated_xml_files', 'xml_content',
               existing_type=sa.NVARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'),
               comment='The actual XML content of the invoice',
               existing_nullable=False)
    op.alter_column('generated_xml_files', 'file_path',
               existing_type=sa.NVARCHAR(length=500, collation='SQL_Latin1_General_CP1_CI_AS'),
               comment='Filesystem path where the XML is stored',
               existing_nullable=True)
    op.alter_column('generated_xml_files', 'file_size',
               existing_type=sa.BIGINT(),
               comment='Size of the XML file in bytes',
               existing_nullable=True)
    op.alter_column('generated_xml_files', 'xml_version',
               existing_type=sa.NVARCHAR(length=10, collation='SQL_Latin1_General_CP1_CI_AS'),
               server_default=None,
               nullable=False,
               comment='TEIF XML schema version')
    op.alter_column('generated_xml_files', 'validation_status',
               existing_type=sa.NVARCHAR(length=50, collation='SQL_Latin1_General_CP1_CI_AS'),
               server_default=None,
               nullable=False,
               comment='Current validation status')
    op.alter_column('generated_xml_files', 'validation_errors',
               existing_type=sa.NVARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'),
               comment='Any validation errors encountered',
               existing_nullable=True)
    op.alter_column('generated_xml_files', 'schema_validation',
               existing_type=mssql.BIT(),
               server_default=None,
               nullable=False,
               comment='Whether the XML passed schema validation')
    op.alter_column('generated_xml_files', 'signature_validation',
               existing_type=mssql.BIT(),
               server_default=None,
               nullable=False,
               comment='Whether the XML signature is valid')
    op.alter_column('generated_xml_files', 'generated_at',
               existing_type=mssql.DATETIME2(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               type_=sa.DateTime(),
               nullable=False,
               comment='When this XML file was generated')
    op.alter_column('invoice_dates', 'invoice_id',
               existing_type=sa.INTEGER(),
               comment='Reference to the parent invoice',
               existing_nullable=False)
    op.alter_column('invoice_dates', 'date_text',
               existing_type=sa.NVARCHAR(length=50, collation='SQL_Latin1_General_CP1_CI_AS'),
               comment='Date in specified format (ddMMyy or ddMMyy-ddMMyy)',
               existing_nullable=False)
    op.alter_column('invoice_dates', 'function_code',
               existing_type=sa.NVARCHAR(length=10, collation='SQL_Latin1_General_CP1_CI_AS'),
               comment='Date function code (I-31, I-32, I-36, etc.)',
               existing_nullable=False)
    op.alter_column('invoice_dates', 'date_format',
               existing_type=sa.NVARCHAR(length=20, collation='SQL_Latin1_General_CP1_CI_AS'),
               comment='Date format (ddMMyy, ddMMyy-ddMMyy, etc.)',
               existing_nullable=False)
    op.alter_column('invoice_dates', 'description',
               existing_type=sa.NVARCHAR(length=255, collation='SQL_Latin1_General_CP1_CI_AS'),
               comment='Optional description of the date',
               existing_nullable=True)
    op.alter_column('invoice_dates', 'created_at',
               existing_type=mssql.DATETIME2(),
               server_default=None,
               type_=sa.DateTime(),
               nullable=False)
    op.alter_column('invoice_lines', 'invoice_id',
               existing_type=sa.INTEGER(),
               comment='Reference to the parent invoice',
               existing_nullable=False)
    op.alter_column('invoice_lines', 'line_number',
               existing_type=sa.INTEGER(),
               comment='Line number in the invoice (I-70)',
               existing_nullable=False)
    op.alter_column('invoice_lines', 'parent_line_id',
               existing_type=sa.INTEGER(),
               comment='Reference to parent line for sub-lines',
               existing_nullable=True)
    op.alter_column('invoice_lines', 'item_identifier',
               existing_type=sa.NVARCHAR(length=100, collation='SQL_Latin1_General_CP1_CI_AS'),
               comment="Item identifier (e.g., 'DDM-001', 'DDR-001', 'KIT-001') (I-71)",
               existing_nullable=True)
    op.alter_column('invoice_lines', 'item_code',
               existing_type=sa.NVARCHAR(length=100, collation='SQL_Latin1_General_CP1_CI_AS'),
               comment='Item code (I-72)',
               existing_nullable=True)
    op.alter_column('invoice_lines', 'description',
               existing_type=sa.NVARCHAR(length=1000, collation='SQL_Latin1_General_CP1_CI_AS'),
               type_=sa.Text(),
               comment='Detailed item description (I-73)',
               existing_nullable=False)
    op.alter_column('invoice_lines', 'quantity',
               existing_type=sa.DECIMAL(precision=10, scale=3),
               comment='Item quantity (I-74)',
               existing_nullable=False)
    op.alter_column('invoice_lines', 'unit',
               existing_type=sa.NVARCHAR(length=10, collation='SQL_Latin1_General_CP1_CI_AS'),
               server_default=None,
               nullable=False,
               comment="Unit of measure (e.g., 'PCE', 'KIT') (I-75)")
    op.alter_column('invoice_lines', 'unit_price',
               existing_type=sa.DECIMAL(precision=15, scale=3),
               comment='Unit price excluding tax (I-76)',
               existing_nullable=False)
    op.alter_column('invoice_lines', 'line_total_ht',
               existing_type=sa.DECIMAL(precision=15, scale=3),
               comment='Line total excluding tax (quantity * unit_price) (I-77)',
               existing_nullable=False)
    op.alter_column('invoice_lines', 'discount_amount',
               existing_type=sa.DECIMAL(precision=15, scale=3),
               server_default=None,
               nullable=False,
               comment='Discount amount for this line (I-78)')
    op.alter_column('invoice_lines', 'discount_reason',
               existing_type=sa.NVARCHAR(length=255, collation='SQL_Latin1_General_CP1_CI_AS'),
               comment="Reason for discount (e.g., 'Special 10% discount') (I-79)",
               existing_nullable=True)
    op.alter_column('invoice_lines', 'currency',
               existing_type=sa.NVARCHAR(length=3, collation='SQL_Latin1_General_CP1_CI_AS'),
               server_default=None,
               nullable=False,
               comment='Currency code (ISO 4217)')
    op.alter_column('invoice_lines', 'line_date',
               existing_type=sa.DATE(),
               comment='Date specific to this line (e.g., service date) (I-80)',
               existing_nullable=True)
    op.alter_column('invoice_lines', 'additional_info',
               existing_type=sa.VARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'),
               comment='Additional line-specific information in JSON format',
               existing_comment='Additional information in JSON format',
               existing_nullable=True)
    op.alter_column('invoice_lines', 'created_at',
               existing_type=mssql.DATETIME2(),
               server_default=None,
               type_=sa.DateTime(),
               nullable=False)
    op.drop_index(op.f('IX_invoice_lines_invoice'), table_name='invoice_lines')
    op.drop_index(op.f('IX_invoice_lines_parent'), table_name='invoice_lines')
    op.create_index('idx_invoice_line_number', 'invoice_lines', ['invoice_id', 'line_number'], unique=False)
    op.create_index('idx_invoice_line_parent', 'invoice_lines', ['parent_line_id'], unique=False)
    op.create_index(op.f('ix_invoice_lines_invoice_id'), 'invoice_lines', ['invoice_id'], unique=False)
    op.create_index(op.f('ix_invoice_lines_parent_line_id'), 'invoice_lines', ['parent_line_id'], unique=False)
    op.create_table_comment(
        'invoice_lines',
        'Invoice line items with TEIF 1.8.8 compliance',
        existing_comment=None,
        schema=None
    )
    op.drop_column('invoice_lines', 'updated_at')
    op.drop_column('invoice_lines', 'currency_code_list')
    op.alter_column('invoice_monetary_amounts', 'invoice_id',
               existing_type=sa.INTEGER(),
               comment='Reference to the invoice',
               existing_nullable=False)
    op.alter_column('invoice_monetary_amounts', 'amount_type_code',
               existing_type=sa.NVARCHAR(length=10, collation='SQL_Latin1_General_CP1_CI_AS'),
               comment="Type code (e.g., 'I-181' for Tax Amount, 'I-182' for Taxable Amount)",
               existing_nullable=False)
    op.alter_column('invoice_monetary_amounts', 'amount',
               existing_type=sa.DECIMAL(precision=15, scale=3),
               comment='Monetary amount',
               existing_nullable=False)
    op.alter_column('invoice_monetary_amounts', 'description',
               existing_type=sa.NVARCHAR(length=255, collation='SQL_Latin1_General_CP1_CI_AS'),
               comment="Description of the amount (e.g., 'Total hors taxes')",
               existing_nullable=True)
    op.alter_column('invoice_monetary_amounts', 'currency',
               existing_type=sa.NVARCHAR(length=3, collation='SQL_Latin1_General_CP1_CI_AS'),
               server_default=None,
               nullable=False,
               comment='Currency code (ISO 4217)')
    op.alter_column('invoice_monetary_amounts', 'currency_code_list',
               existing_type=sa.NVARCHAR(length=20, collation='SQL_Latin1_General_CP1_CI_AS'),
               server_default=None,
               nullable=False,
               comment='Currency code list identifier')
    op.alter_column('invoice_monetary_amounts', 'created_at',
               existing_type=mssql.DATETIME2(),
               server_default=None,
               type_=sa.DateTime(),
               nullable=False)
    op.create_index(op.f('ix_invoice_monetary_amounts_invoice_id'), 'invoice_monetary_amounts', ['invoice_id'], unique=False)
    op.alter_column('invoice_references', 'invoice_id',
               existing_type=sa.INTEGER(),
               comment='Reference to the parent invoice',
               existing_nullable=False)
    op.alter_column('invoice_references', 'reference_type',
               existing_type=sa.NVARCHAR(length=10, collation='SQL_Latin1_General_CP1_CI_AS'),
               comment="Reference type code (e.g., 'I-04' for Purchase Order, 'I-05' for Contract)",
               existing_nullable=False)
    op.alter_column('invoice_references', 'reference_number',
               existing_type=sa.VARCHAR(length=100, collation='SQL_Latin1_General_CP1_CI_AS'),
               server_default=None,
               existing_comment='Reference number or identifier',
               existing_nullable=False)
    op.alter_column('invoice_references', 'description',
               existing_type=sa.NVARCHAR(length=255, collation='SQL_Latin1_General_CP1_CI_AS'),
               comment='Optional description of the reference',
               existing_nullable=True)
    op.alter_column('invoice_references', 'created_at',
               existing_type=mssql.DATETIME2(),
               server_default=None,
               type_=sa.DateTime(),
               nullable=False)
    op.create_index('idx_invoice_ref_type', 'invoice_references', ['invoice_id', 'reference_type'], unique=False)
    op.create_table_comment(
        'invoice_references',
        'Invoice references and identifiers',
        existing_comment=None,
        schema=None
    )
    op.drop_column('invoice_references', 'reference_value')
    op.add_column('invoice_signatures', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.alter_column('invoice_signatures', 'invoice_id',
               existing_type=sa.INTEGER(),
               comment='Reference to the signed invoice',
               existing_nullable=False)
    op.alter_column('invoice_signatures', 'signature_id',
               existing_type=sa.NVARCHAR(length=50, collation='SQL_Latin1_General_CP1_CI_AS'),
               comment='Unique identifier for the signature',
               existing_nullable=False)
    op.alter_column('invoice_signatures', 'signer_role',
               existing_type=sa.NVARCHAR(length=50, collation='SQL_Latin1_General_CP1_CI_AS'),
               comment="Role of the signer (e.g., 'Fournisseur')",
               existing_nullable=True)
    op.alter_column('invoice_signatures', 'signer_name',
               existing_type=sa.NVARCHAR(length=255, collation='SQL_Latin1_General_CP1_CI_AS'),
               comment='Name of the signer',
               existing_nullable=True)
    op.alter_column('invoice_signatures', 'x509_certificate',
               existing_type=sa.NVARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'),
               comment='X.509 certificate in base64 format',
               existing_nullable=True)
    op.alter_column('invoice_signatures', 'private_key_data',
               existing_type=sa.NVARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'),
               comment='Private key data (for testing only)',
               existing_nullable=True)
    op.alter_column('invoice_signatures', 'key_password',
               existing_type=sa.NVARCHAR(length=255, collation='SQL_Latin1_General_CP1_CI_AS'),
               comment='Key password (encrypted)',
               existing_nullable=True)
    op.alter_column('invoice_signatures', 'signing_time',
               existing_type=mssql.DATETIME2(),
               type_=sa.DateTime(),
               comment='Timestamp when the signature was created (ISO format)',
               existing_nullable=True)
    op.alter_column('invoice_signatures', 'signature_value',
               existing_type=sa.NVARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'),
               comment='Computed signature value',
               existing_nullable=True)
    op.alter_column('invoice_signatures', 'signature_status',
               existing_type=sa.NVARCHAR(length=50, collation='SQL_Latin1_General_CP1_CI_AS'),
               server_default=None,
               nullable=False,
               comment="Signature status: 'pending', 'signed', 'verified', or 'invalid'")
    op.alter_column('invoice_signatures', 'verification_date',
               existing_type=mssql.DATETIME2(),
               type_=sa.DateTime(),
               comment='When the signature was last verified',
               existing_nullable=True)
    op.alter_column('invoice_signatures', 'verification_result',
               existing_type=sa.NVARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'),
               comment='Detailed result of the signature verification',
               existing_nullable=True)
    op.alter_column('invoice_signatures', 'created_at',
               existing_type=mssql.DATETIME2(),
               server_default=None,
               type_=sa.DateTime(),
               nullable=False)
    op.drop_index(op.f('IX_signatures_invoice'), table_name='invoice_signatures')
    op.drop_index(op.f('IX_signatures_status'), table_name='invoice_signatures')
    op.create_index(op.f('ix_invoice_signatures_invoice_id'), 'invoice_signatures', ['invoice_id'], unique=False)
    op.create_index(op.f('ix_invoice_signatures_signature_status'), 'invoice_signatures', ['signature_status'], unique=False)
    op.alter_column('invoice_taxes', 'invoice_id',
               existing_type=sa.INTEGER(),
               comment='Reference to the invoice',
               existing_nullable=False)
    op.alter_column('invoice_taxes', 'tax_code',
               existing_type=sa.NVARCHAR(length=10, collation='SQL_Latin1_General_CP1_CI_AS'),
               comment="Tax code (e.g., 'I-1602' for VAT, 'I-1601' for Stamp Duty)",
               existing_nullable=False)
    op.alter_column('invoice_taxes', 'tax_type',
               existing_type=sa.NVARCHAR(length=50, collation='SQL_Latin1_General_CP1_CI_AS'),
               comment="Type of tax (e.g., 'TVA', 'Droit de timbre')",
               existing_nullable=False)
    op.alter_column('invoice_taxes', 'tax_category',
               existing_type=sa.NVARCHAR(length=10, collation='SQL_Latin1_General_CP1_CI_AS'),
               comment="Tax category (e.g., 'S' for Standard, 'E' for Exempt)",
               existing_nullable=True)
    op.alter_column('invoice_taxes', 'tax_rate',
               existing_type=sa.DECIMAL(precision=5, scale=2),
               comment='Tax rate as a percentage (e.g., 19.0 for 19%)',
               existing_nullable=False)
    op.alter_column('invoice_taxes', 'taxable_amount',
               existing_type=sa.DECIMAL(precision=15, scale=3),
               comment='Taxable base amount',
               existing_nullable=False)
    op.alter_column('invoice_taxes', 'tax_amount',
               existing_type=sa.DECIMAL(precision=15, scale=3),
               comment='Calculated tax amount',
               existing_nullable=False)
    op.alter_column('invoice_taxes', 'created_at',
               existing_type=mssql.DATETIME2(),
               server_default=None,
               type_=sa.DateTime(),
               nullable=False)
    op.drop_index(op.f('IX_invoice_taxes_invoice'), table_name='invoice_taxes')
    op.create_index(op.f('ix_invoice_taxes_invoice_id'), 'invoice_taxes', ['invoice_id'], unique=False)
    op.drop_column('invoice_taxes', 'currency_code_list')
    op.alter_column('invoices', 'teif_version',
               existing_type=sa.NVARCHAR(length=10, collation='SQL_Latin1_General_CP1_CI_AS'),
               server_default=None,
               nullable=False,
               comment='TEIF standard version (I-08)')
    op.alter_column('invoices', 'controlling_agency',
               existing_type=sa.NVARCHAR(length=10, collation='SQL_Latin1_General_CP1_CI_AS'),
               server_default=None,
               nullable=False,
               comment='Controlling agency (e.g., TTN) (I-09)')
    op.alter_column('invoices', 'sender_identifier',
               existing_type=sa.NVARCHAR(length=50, collation='SQL_Latin1_General_CP1_CI_AS'),
               comment="Sender's unique identifier (I-02)",
               existing_nullable=False)
    op.alter_column('invoices', 'receiver_identifier',
               existing_type=sa.NVARCHAR(length=50, collation='SQL_Latin1_General_CP1_CI_AS'),
               comment="Receiver's unique identifier (I-03)",
               existing_nullable=False)
    op.alter_column('invoices', 'message_identifier',
               existing_type=sa.NVARCHAR(length=100, collation='SQL_Latin1_General_CP1_CI_AS'),
               comment='Unique message identifier (I-04)',
               existing_nullable=True)
    op.alter_column('invoices', 'message_datetime',
               existing_type=mssql.DATETIME2(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               type_=sa.DateTime(),
               nullable=False,
               comment='Message creation timestamp (I-05)')
    op.alter_column('invoices', 'document_number',
               existing_type=sa.NVARCHAR(length=100, collation='SQL_Latin1_General_CP1_CI_AS'),
               comment='Invoice document number (I-06)',
               existing_nullable=False)
    op.alter_column('invoices', 'document_type',
               existing_type=sa.NVARCHAR(length=10, collation='SQL_Latin1_General_CP1_CI_AS'),
               server_default=None,
               nullable=False,
               comment='Document type code (I-11)')
    op.alter_column('invoices', 'document_type_label',
               existing_type=sa.NVARCHAR(length=100, collation='SQL_Latin1_General_CP1_CI_AS'),
               server_default=None,
               nullable=False,
               comment='Document type label (I-12)')
    op.alter_column('invoices', 'status',
               existing_type=sa.NVARCHAR(length=50, collation='SQL_Latin1_General_CP1_CI_AS'),
               server_default=None,
               type_=sa.String(length=20),
               comment='Current status of the invoice',
               existing_nullable=False)
    op.alter_column('invoices', 'invoice_date',
               existing_type=sa.DATE(),
               comment='Invoice issue date (I-31)',
               existing_nullable=False)
    op.alter_column('invoices', 'due_date',
               existing_type=sa.DATE(),
               comment='Payment due date (I-32)',
               existing_nullable=True)
    op.alter_column('invoices', 'period_start_date',
               existing_type=sa.DATE(),
               comment='Start date of the billing period (I-33)',
               existing_nullable=True)
    op.alter_column('invoices', 'period_end_date',
               existing_type=sa.DATE(),
               comment='End date of the billing period (I-34)',
               existing_nullable=True)
    op.alter_column('invoices', 'supplier_id',
               existing_type=sa.INTEGER(),
               comment='Reference to the supplier company',
               existing_nullable=False)
    op.alter_column('invoices', 'customer_id',
               existing_type=sa.INTEGER(),
               comment='Reference to the customer company',
               existing_nullable=False)
    op.alter_column('invoices', 'currency',
               existing_type=sa.NVARCHAR(length=3, collation='SQL_Latin1_General_CP1_CI_AS'),
               server_default=None,
               nullable=False,
               comment='Invoice currency code (ISO 4217) (I-07)')
    op.alter_column('invoices', 'currency_code_list',
               existing_type=sa.NVARCHAR(length=20, collation='SQL_Latin1_General_CP1_CI_AS'),
               server_default=None,
               nullable=False,
               comment='Currency code list name')
    op.alter_column('invoices', 'capital_amount',
               existing_type=sa.DECIMAL(precision=15, scale=3),
               server_default=None,
               nullable=False,
               comment='Total capital amount (I-179)')
    op.alter_column('invoices', 'total_with_tax',
               existing_type=sa.DECIMAL(precision=15, scale=3),
               server_default=None,
               nullable=False,
               comment='Total amount including tax (I-180)')
    op.alter_column('invoices', 'total_without_tax',
               existing_type=sa.DECIMAL(precision=15, scale=3),
               server_default=None,
               nullable=False,
               comment='Total amount excluding tax (I-176)')
    op.alter_column('invoices', 'tax_base_amount',
               existing_type=sa.DECIMAL(precision=15, scale=3),
               server_default=None,
               nullable=False,
               comment='Tax base amount (I-182)')
    op.alter_column('invoices', 'tax_amount',
               existing_type=sa.DECIMAL(precision=15, scale=3),
               server_default=None,
               nullable=False,
               comment='Total tax amount (I-181)')
    op.alter_column('invoices', 'notes',
               existing_type=sa.VARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'),
               comment='Additional notes or comments',
               existing_comment='Additional notes or terms for the invoice',
               existing_nullable=True)
    op.alter_column('invoices', 'updated_at',
               existing_type=mssql.DATETIME2(),
               server_default=None,
               type_=sa.DateTime(),
               existing_nullable=True)
    op.alter_column('invoices', 'created_at',
               existing_type=mssql.DATETIME2(),
               server_default=None,
               type_=sa.DateTime(),
               nullable=False)
    op.drop_index(op.f('IX_invoices_customer'), table_name='invoices')
    op.drop_index(op.f('IX_invoices_document_number'), table_name='invoices')
    op.drop_index(op.f('IX_invoices_invoice_date'), table_name='invoices')
    op.drop_index(op.f('IX_invoices_status'), table_name='invoices')
    op.drop_index(op.f('IX_invoices_supplier'), table_name='invoices')
    op.drop_index(op.f('idx_invoice_delivery_party'), table_name='invoices')
    op.drop_index(op.f('idx_invoice_status'), table_name='invoices')
    op.create_index('idx_invoice_customer', 'invoices', ['customer_id'], unique=False)
    op.create_index('idx_invoice_dates', 'invoices', ['invoice_date', 'due_date'], unique=False)
    op.create_index('idx_invoice_document_number', 'invoices', ['document_number'], unique=False)
    op.create_index('idx_invoice_supplier', 'invoices', ['supplier_id'], unique=False)
    op.create_index(op.f('ix_invoices_customer_id'), 'invoices', ['customer_id'], unique=False)
    op.create_index(op.f('ix_invoices_document_number'), 'invoices', ['document_number'], unique=False)
    op.create_index(op.f('ix_invoices_invoice_date'), 'invoices', ['invoice_date'], unique=False)
    op.create_index(op.f('ix_invoices_supplier_id'), 'invoices', ['supplier_id'], unique=False)
    op.create_table_comment(
        'invoices',
        'Invoices with TEIF 1.8.8 compliance',
        existing_comment=None,
        schema=None
    )
    op.drop_column('invoices', 'pdf_path')
    op.drop_column('invoices', 'xml_path')
    op.drop_column('invoices', 'document_status')
    op.drop_column('invoices', 'ttn_validation_ref')
    op.alter_column('line_taxes', 'line_id',
               existing_type=sa.INTEGER(),
               comment='Reference to the invoice line',
               existing_nullable=False)
    op.alter_column('line_taxes', 'tax_code',
               existing_type=sa.NVARCHAR(length=10, collation='SQL_Latin1_General_CP1_CI_AS'),
               comment="Tax code (e.g., 'I-1602' for VAT, 'I-1601' for Stamp Duty)",
               existing_nullable=False)
    op.alter_column('line_taxes', 'tax_type',
               existing_type=sa.NVARCHAR(length=50, collation='SQL_Latin1_General_CP1_CI_AS'),
               comment="Type of tax (e.g., 'TVA', 'Droit de timbre')",
               existing_nullable=False)
    op.alter_column('line_taxes', 'tax_category',
               existing_type=sa.NVARCHAR(length=10, collation='SQL_Latin1_General_CP1_CI_AS'),
               comment="Tax category (e.g., 'S' for Standard, 'E' for Exempt, 'Z' for Zero-rated)",
               existing_nullable=True)
    op.alter_column('line_taxes', 'tax_rate',
               existing_type=sa.DECIMAL(precision=5, scale=2),
               comment='Tax rate as a percentage (e.g., 19.0 for 19%)',
               existing_nullable=False)
    op.alter_column('line_taxes', 'taxable_amount',
               existing_type=sa.DECIMAL(precision=15, scale=3),
               comment='Taxable base amount',
               existing_nullable=False)
    op.alter_column('line_taxes', 'tax_amount',
               existing_type=sa.DECIMAL(precision=15, scale=3),
               comment='Calculated tax amount',
               existing_nullable=False)
    op.alter_column('line_taxes', 'currency_code_list',
               existing_type=sa.NVARCHAR(length=20, collation='SQL_Latin1_General_CP1_CI_AS'),
               server_default=None,
               nullable=False,
               comment='Currency code list identifier')
    op.alter_column('line_taxes', 'created_at',
               existing_type=mssql.DATETIME2(),
               server_default=None,
               type_=sa.DateTime(),
               nullable=False)
    op.drop_index(op.f('IX_line_taxes_line'), table_name='line_taxes')
    op.add_column('payment_means', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.alter_column('payment_means', 'invoice_id',
               existing_type=sa.INTEGER(),
               comment='Reference to the parent invoice',
               existing_nullable=False)
    op.alter_column('payment_means', 'payment_means_code',
               existing_type=sa.NVARCHAR(length=10, collation='SQL_Latin1_General_CP1_CI_AS'),
               comment="Payment means code (e.g., 'I-30')",
               existing_nullable=True)
    op.alter_column('payment_means', 'payment_id',
               existing_type=sa.NVARCHAR(length=100, collation='SQL_Latin1_General_CP1_CI_AS'),
               comment="Payment reference or transaction ID (e.g., 'VIR-2023-001')",
               existing_nullable=True)
    op.alter_column('payment_means', 'due_date',
               existing_type=sa.DATE(),
               comment='Due date for this payment method',
               existing_nullable=True)
    op.alter_column('payment_means', 'iban',
               existing_type=sa.NVARCHAR(length=50, collation='SQL_Latin1_General_CP1_CI_AS'),
               comment="IBAN of the beneficiary's account (e.g., 'TN5904018104003691234567')",
               existing_nullable=True)
    op.alter_column('payment_means', 'account_holder',
               existing_type=sa.NVARCHAR(length=255, collation='SQL_Latin1_General_CP1_CI_AS'),
               comment='Name of the account holder',
               existing_nullable=True)
    op.alter_column('payment_means', 'financial_institution',
               existing_type=sa.NVARCHAR(length=255, collation='SQL_Latin1_General_CP1_CI_AS'),
               comment="Name of the financial institution (e.g., 'BNA')",
               existing_nullable=True)
    op.alter_column('payment_means', 'branch_code',
               existing_type=sa.NVARCHAR(length=50, collation='SQL_Latin1_General_CP1_CI_AS'),
               comment="Branch code or identifier (e.g., 'AGENCE_123')",
               existing_nullable=True)
    op.alter_column('payment_means', 'created_at',
               existing_type=mssql.DATETIME2(),
               server_default=None,
               type_=sa.DateTime(),
               nullable=False)
    op.add_column('payment_terms', sa.Column('due_date', sa.Date(), nullable=True, comment='The date by which the payment is due'))
    op.add_column('payment_terms', sa.Column('payment_reference', sa.String(length=50), nullable=True, comment='Payment reference or identifier'))
    op.add_column('payment_terms', sa.Column('notes', sa.String(length=500), nullable=True, comment='Any additional notes about the payment terms'))
    op.alter_column('payment_terms', 'invoice_id',
               existing_type=sa.INTEGER(),
               comment='Reference to the parent invoice',
               existing_nullable=False)
    op.alter_column('payment_terms', 'payment_terms_code',
               existing_type=sa.NVARCHAR(length=10, collation='SQL_Latin1_General_CP1_CI_AS'),
               comment="Payment terms code (e.g., 'I-37' for payment terms)",
               existing_nullable=True)
    op.alter_column('payment_terms', 'discount_percent',
               existing_type=sa.DECIMAL(precision=5, scale=2),
               comment='Discount percentage for early payment (e.g., 2.0 for 2%)',
               existing_nullable=True)
    op.alter_column('payment_terms', 'discount_due_date',
               existing_type=sa.DATE(),
               comment='Last date to take advantage of the early payment discount',
               existing_nullable=True)
    op.alter_column('payment_terms', 'created_at',
               existing_type=mssql.DATETIME2(),
               server_default=None,
               type_=sa.DateTime(),
               nullable=False)
    op.create_index(op.f('ix_payment_terms_id'), 'payment_terms', ['id'], unique=False)
    op.create_table_comment(
        'payment_terms',
        'Payment terms for invoices',
        existing_comment=None,
        schema=None
    )
    op.drop_column('payment_terms', 'updated_at')
    op.drop_column('payment_terms', 'description')
    op.drop_column('payment_terms', 'payment_due_date')
    op.add_column('special_conditions', sa.Column('base_amount', sa.Numeric(precision=15, scale=3), nullable=True, comment='Base amount for percentage calculations'))
    op.add_column('special_conditions', sa.Column('percentage', sa.Numeric(precision=5, scale=2), nullable=True, comment='Percentage rate (0-100) if applicable'))
    op.alter_column('special_conditions', 'invoice_id',
               existing_type=sa.INTEGER(),
               comment='Reference to the parent invoice',
               existing_nullable=False)
    op.alter_column('special_conditions', 'condition_type',
               existing_type=sa.VARCHAR(length=10, collation='SQL_Latin1_General_CP1_CI_AS'),
               server_default=None,
               comment="Condition type code (e.g., 'I-01' for Discount, 'I-02' for Surcharge)",
               existing_comment='Condition type code (e.g., "I-01" for Discount, "I-02" for Surcharge)',
               existing_nullable=False)
    op.alter_column('special_conditions', 'description',
               existing_type=sa.VARCHAR(length=500, collation='SQL_Latin1_General_CP1_CI_AS'),
               server_default=None,
               existing_comment='Description of the special condition',
               existing_nullable=False)
    op.alter_column('special_conditions', 'amount',
               existing_type=sa.NUMERIC(precision=15, scale=3),
               server_default=None,
               existing_comment='Amount of the special condition',
               existing_nullable=False)
    op.alter_column('special_conditions', 'currency',
               existing_type=sa.VARCHAR(length=3, collation='SQL_Latin1_General_CP1_CI_AS'),
               server_default=None,
               existing_comment='Currency code (ISO 4217)',
               existing_nullable=False)
    op.alter_column('special_conditions', 'created_at',
               existing_type=mssql.DATETIME2(),
               server_default=None,
               type_=sa.DateTime(),
               nullable=False)
    op.create_table_comment(
        'special_conditions',
        'Special conditions and terms for invoices',
        existing_comment=None,
        schema=None
    )
    op.drop_column('special_conditions', 'language_code')
    op.drop_column('special_conditions', 'condition_text')
    op.drop_column('special_conditions', 'sequence_number')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('special_conditions', sa.Column('sequence_number', sa.INTEGER(), server_default=sa.text('((1))'), autoincrement=False, nullable=True))
    op.add_column('special_conditions', sa.Column('condition_text', sa.NVARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=False))
    op.add_column('special_conditions', sa.Column('language_code', sa.NVARCHAR(length=2, collation='SQL_Latin1_General_CP1_CI_AS'), server_default=sa.text("('fr')"), autoincrement=False, nullable=True))
    op.drop_table_comment(
        'special_conditions',
        existing_comment='Special conditions and terms for invoices',
        schema=None
    )
    op.alter_column('special_conditions', 'created_at',
               existing_type=sa.DateTime(),
               server_default=sa.text('(getdate())'),
               type_=mssql.DATETIME2(),
               nullable=True)
    op.alter_column('special_conditions', 'currency',
               existing_type=sa.VARCHAR(length=3, collation='SQL_Latin1_General_CP1_CI_AS'),
               server_default=sa.text("('TND')"),
               existing_comment='Currency code (ISO 4217)',
               existing_nullable=False)
    op.alter_column('special_conditions', 'amount',
               existing_type=sa.NUMERIC(precision=15, scale=3),
               server_default=sa.text("('0')"),
               existing_comment='Amount of the special condition',
               existing_nullable=False)
    op.alter_column('special_conditions', 'description',
               existing_type=sa.VARCHAR(length=500, collation='SQL_Latin1_General_CP1_CI_AS'),
               server_default=sa.text("('')"),
               existing_comment='Description of the special condition',
               existing_nullable=False)
    op.alter_column('special_conditions', 'condition_type',
               existing_type=sa.VARCHAR(length=10, collation='SQL_Latin1_General_CP1_CI_AS'),
               server_default=sa.text("('I-01')"),
               comment='Condition type code (e.g., "I-01" for Discount, "I-02" for Surcharge)',
               existing_comment="Condition type code (e.g., 'I-01' for Discount, 'I-02' for Surcharge)",
               existing_nullable=False)
    op.alter_column('special_conditions', 'invoice_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Reference to the parent invoice',
               existing_nullable=False)
    op.drop_column('special_conditions', 'percentage')
    op.drop_column('special_conditions', 'base_amount')
    op.add_column('payment_terms', sa.Column('payment_due_date', sa.DATE(), autoincrement=False, nullable=True))
    op.add_column('payment_terms', sa.Column('description', sa.NVARCHAR(length=500, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True))
    op.add_column('payment_terms', sa.Column('updated_at', sa.DATETIME(), server_default=sa.text('(getdate())'), autoincrement=False, nullable=True))
    op.drop_table_comment(
        'payment_terms',
        existing_comment='Payment terms for invoices',
        schema=None
    )
    op.drop_index(op.f('ix_payment_terms_id'), table_name='payment_terms')
    op.alter_column('payment_terms', 'created_at',
               existing_type=sa.DateTime(),
               server_default=sa.text('(getdate())'),
               type_=mssql.DATETIME2(),
               nullable=True)
    op.alter_column('payment_terms', 'discount_due_date',
               existing_type=sa.DATE(),
               comment=None,
               existing_comment='Last date to take advantage of the early payment discount',
               existing_nullable=True)
    op.alter_column('payment_terms', 'discount_percent',
               existing_type=sa.DECIMAL(precision=5, scale=2),
               comment=None,
               existing_comment='Discount percentage for early payment (e.g., 2.0 for 2%)',
               existing_nullable=True)
    op.alter_column('payment_terms', 'payment_terms_code',
               existing_type=sa.NVARCHAR(length=10, collation='SQL_Latin1_General_CP1_CI_AS'),
               comment=None,
               existing_comment="Payment terms code (e.g., 'I-37' for payment terms)",
               existing_nullable=True)
    op.alter_column('payment_terms', 'invoice_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Reference to the parent invoice',
               existing_nullable=False)
    op.drop_column('payment_terms', 'notes')
    op.drop_column('payment_terms', 'payment_reference')
    op.drop_column('payment_terms', 'due_date')
    op.alter_column('payment_means', 'created_at',
               existing_type=sa.DateTime(),
               server_default=sa.text('(getdate())'),
               type_=mssql.DATETIME2(),
               nullable=True)
    op.alter_column('payment_means', 'branch_code',
               existing_type=sa.NVARCHAR(length=50, collation='SQL_Latin1_General_CP1_CI_AS'),
               comment=None,
               existing_comment="Branch code or identifier (e.g., 'AGENCE_123')",
               existing_nullable=True)
    op.alter_column('payment_means', 'financial_institution',
               existing_type=sa.NVARCHAR(length=255, collation='SQL_Latin1_General_CP1_CI_AS'),
               comment=None,
               existing_comment="Name of the financial institution (e.g., 'BNA')",
               existing_nullable=True)
    op.alter_column('payment_means', 'account_holder',
               existing_type=sa.NVARCHAR(length=255, collation='SQL_Latin1_General_CP1_CI_AS'),
               comment=None,
               existing_comment='Name of the account holder',
               existing_nullable=True)
    op.alter_column('payment_means', 'iban',
               existing_type=sa.NVARCHAR(length=50, collation='SQL_Latin1_General_CP1_CI_AS'),
               comment=None,
               existing_comment="IBAN of the beneficiary's account (e.g., 'TN5904018104003691234567')",
               existing_nullable=True)
    op.alter_column('payment_means', 'due_date',
               existing_type=sa.DATE(),
               comment=None,
               existing_comment='Due date for this payment method',
               existing_nullable=True)
    op.alter_column('payment_means', 'payment_id',
               existing_type=sa.NVARCHAR(length=100, collation='SQL_Latin1_General_CP1_CI_AS'),
               comment=None,
               existing_comment="Payment reference or transaction ID (e.g., 'VIR-2023-001')",
               existing_nullable=True)
    op.alter_column('payment_means', 'payment_means_code',
               existing_type=sa.NVARCHAR(length=10, collation='SQL_Latin1_General_CP1_CI_AS'),
               comment=None,
               existing_comment="Payment means code (e.g., 'I-30')",
               existing_nullable=True)
    op.alter_column('payment_means', 'invoice_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Reference to the parent invoice',
               existing_nullable=False)
    op.drop_column('payment_means', 'updated_at')
    op.create_index(op.f('IX_line_taxes_line'), 'line_taxes', ['line_id'], unique=False)
    op.alter_column('line_taxes', 'created_at',
               existing_type=sa.DateTime(),
               server_default=sa.text('(getdate())'),
               type_=mssql.DATETIME2(),
               nullable=True)
    op.alter_column('line_taxes', 'currency_code_list',
               existing_type=sa.NVARCHAR(length=20, collation='SQL_Latin1_General_CP1_CI_AS'),
               server_default=sa.text("('ISO_4217')"),
               nullable=True,
               comment=None,
               existing_comment='Currency code list identifier')
    op.alter_column('line_taxes', 'tax_amount',
               existing_type=sa.DECIMAL(precision=15, scale=3),
               comment=None,
               existing_comment='Calculated tax amount',
               existing_nullable=False)
    op.alter_column('line_taxes', 'taxable_amount',
               existing_type=sa.DECIMAL(precision=15, scale=3),
               comment=None,
               existing_comment='Taxable base amount',
               existing_nullable=False)
    op.alter_column('line_taxes', 'tax_rate',
               existing_type=sa.DECIMAL(precision=5, scale=2),
               comment=None,
               existing_comment='Tax rate as a percentage (e.g., 19.0 for 19%)',
               existing_nullable=False)
    op.alter_column('line_taxes', 'tax_category',
               existing_type=sa.NVARCHAR(length=10, collation='SQL_Latin1_General_CP1_CI_AS'),
               comment=None,
               existing_comment="Tax category (e.g., 'S' for Standard, 'E' for Exempt, 'Z' for Zero-rated)",
               existing_nullable=True)
    op.alter_column('line_taxes', 'tax_type',
               existing_type=sa.NVARCHAR(length=50, collation='SQL_Latin1_General_CP1_CI_AS'),
               comment=None,
               existing_comment="Type of tax (e.g., 'TVA', 'Droit de timbre')",
               existing_nullable=False)
    op.alter_column('line_taxes', 'tax_code',
               existing_type=sa.NVARCHAR(length=10, collation='SQL_Latin1_General_CP1_CI_AS'),
               comment=None,
               existing_comment="Tax code (e.g., 'I-1602' for VAT, 'I-1601' for Stamp Duty)",
               existing_nullable=False)
    op.alter_column('line_taxes', 'line_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Reference to the invoice line',
               existing_nullable=False)
    op.add_column('invoices', sa.Column('ttn_validation_ref', sa.NVARCHAR(length=100, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True))
    op.add_column('invoices', sa.Column('document_status', sa.VARCHAR(length=20, collation='SQL_Latin1_General_CP1_CI_AS'), server_default=sa.text("('draft')"), autoincrement=False, nullable=False, comment='Current status of the invoice'))
    op.add_column('invoices', sa.Column('xml_path', sa.NVARCHAR(length=500, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True))
    op.add_column('invoices', sa.Column('pdf_path', sa.NVARCHAR(length=500, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True))
    op.drop_table_comment(
        'invoices',
        existing_comment='Invoices with TEIF 1.8.8 compliance',
        schema=None
    )
    op.drop_index(op.f('ix_invoices_supplier_id'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_invoice_date'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_document_number'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_customer_id'), table_name='invoices')
    op.drop_index('idx_invoice_supplier', table_name='invoices')
    op.drop_index('idx_invoice_document_number', table_name='invoices')
    op.drop_index('idx_invoice_dates', table_name='invoices')
    op.drop_index('idx_invoice_customer', table_name='invoices')
    op.create_index(op.f('idx_invoice_status'), 'invoices', ['document_status'], unique=False)
    op.create_index(op.f('idx_invoice_delivery_party'), 'invoices', ['delivery_party_id'], unique=False)
    op.create_index(op.f('IX_invoices_supplier'), 'invoices', ['supplier_id'], unique=False)
    op.create_index(op.f('IX_invoices_status'), 'invoices', ['status'], unique=False)
    op.create_index(op.f('IX_invoices_invoice_date'), 'invoices', ['invoice_date'], unique=False)
    op.create_index(op.f('IX_invoices_document_number'), 'invoices', ['document_number'], unique=False)
    op.create_index(op.f('IX_invoices_customer'), 'invoices', ['customer_id'], unique=False)
    op.alter_column('invoices', 'created_at',
               existing_type=sa.DateTime(),
               server_default=sa.text('(getdate())'),
               type_=mssql.DATETIME2(),
               nullable=True)
    op.alter_column('invoices', 'updated_at',
               existing_type=sa.DateTime(),
               server_default=sa.text('(getdate())'),
               type_=mssql.DATETIME2(),
               existing_nullable=True)
    op.alter_column('invoices', 'notes',
               existing_type=sa.VARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'),
               comment='Additional notes or terms for the invoice',
               existing_comment='Additional notes or comments',
               existing_nullable=True)
    op.alter_column('invoices', 'tax_amount',
               existing_type=sa.DECIMAL(precision=15, scale=3),
               server_default=sa.text('((0))'),
               nullable=True,
               comment=None,
               existing_comment='Total tax amount (I-181)')
    op.alter_column('invoices', 'tax_base_amount',
               existing_type=sa.DECIMAL(precision=15, scale=3),
               server_default=sa.text('((0))'),
               nullable=True,
               comment=None,
               existing_comment='Tax base amount (I-182)')
    op.alter_column('invoices', 'total_without_tax',
               existing_type=sa.DECIMAL(precision=15, scale=3),
               server_default=sa.text('((0))'),
               nullable=True,
               comment=None,
               existing_comment='Total amount excluding tax (I-176)')
    op.alter_column('invoices', 'total_with_tax',
               existing_type=sa.DECIMAL(precision=15, scale=3),
               server_default=sa.text('((0))'),
               nullable=True,
               comment=None,
               existing_comment='Total amount including tax (I-180)')
    op.alter_column('invoices', 'capital_amount',
               existing_type=sa.DECIMAL(precision=15, scale=3),
               server_default=sa.text('((0))'),
               nullable=True,
               comment=None,
               existing_comment='Total capital amount (I-179)')
    op.alter_column('invoices', 'currency_code_list',
               existing_type=sa.NVARCHAR(length=20, collation='SQL_Latin1_General_CP1_CI_AS'),
               server_default=sa.text("('ISO_4217')"),
               nullable=True,
               comment=None,
               existing_comment='Currency code list name')
    op.alter_column('invoices', 'currency',
               existing_type=sa.NVARCHAR(length=3, collation='SQL_Latin1_General_CP1_CI_AS'),
               server_default=sa.text("('TND')"),
               nullable=True,
               comment=None,
               existing_comment='Invoice currency code (ISO 4217) (I-07)')
    op.alter_column('invoices', 'customer_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Reference to the customer company',
               existing_nullable=False)
    op.alter_column('invoices', 'supplier_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Reference to the supplier company',
               existing_nullable=False)
    op.alter_column('invoices', 'period_end_date',
               existing_type=sa.DATE(),
               comment=None,
               existing_comment='End date of the billing period (I-34)',
               existing_nullable=True)
    op.alter_column('invoices', 'period_start_date',
               existing_type=sa.DATE(),
               comment=None,
               existing_comment='Start date of the billing period (I-33)',
               existing_nullable=True)
    op.alter_column('invoices', 'due_date',
               existing_type=sa.DATE(),
               comment=None,
               existing_comment='Payment due date (I-32)',
               existing_nullable=True)
    op.alter_column('invoices', 'invoice_date',
               existing_type=sa.DATE(),
               comment=None,
               existing_comment='Invoice issue date (I-31)',
               existing_nullable=False)
    op.alter_column('invoices', 'status',
               existing_type=sa.String(length=20),
               server_default=sa.text("('draft')"),
               type_=sa.NVARCHAR(length=50, collation='SQL_Latin1_General_CP1_CI_AS'),
               comment=None,
               existing_comment='Current status of the invoice',
               existing_nullable=False)
    op.alter_column('invoices', 'document_type_label',
               existing_type=sa.NVARCHAR(length=100, collation='SQL_Latin1_General_CP1_CI_AS'),
               server_default=sa.text("('Facture')"),
               nullable=True,
               comment=None,
               existing_comment='Document type label (I-12)')
    op.alter_column('invoices', 'document_type',
               existing_type=sa.NVARCHAR(length=10, collation='SQL_Latin1_General_CP1_CI_AS'),
               server_default=sa.text("('I-11')"),
               nullable=True,
               comment=None,
               existing_comment='Document type code (I-11)')
    op.alter_column('invoices', 'document_number',
               existing_type=sa.NVARCHAR(length=100, collation='SQL_Latin1_General_CP1_CI_AS'),
               comment=None,
               existing_comment='Invoice document number (I-06)',
               existing_nullable=False)
    op.alter_column('invoices', 'message_datetime',
               existing_type=sa.DateTime(),
               server_default=sa.text('(getdate())'),
               type_=mssql.DATETIME2(),
               nullable=True,
               comment=None,
               existing_comment='Message creation timestamp (I-05)')
    op.alter_column('invoices', 'message_identifier',
               existing_type=sa.NVARCHAR(length=100, collation='SQL_Latin1_General_CP1_CI_AS'),
               comment=None,
               existing_comment='Unique message identifier (I-04)',
               existing_nullable=True)
    op.alter_column('invoices', 'receiver_identifier',
               existing_type=sa.NVARCHAR(length=50, collation='SQL_Latin1_General_CP1_CI_AS'),
               comment=None,
               existing_comment="Receiver's unique identifier (I-03)",
               existing_nullable=False)
    op.alter_column('invoices', 'sender_identifier',
               existing_type=sa.NVARCHAR(length=50, collation='SQL_Latin1_General_CP1_CI_AS'),
               comment=None,
               existing_comment="Sender's unique identifier (I-02)",
               existing_nullable=False)
    op.alter_column('invoices', 'controlling_agency',
               existing_type=sa.NVARCHAR(length=10, collation='SQL_Latin1_General_CP1_CI_AS'),
               server_default=sa.text("('TTN')"),
               nullable=True,
               comment=None,
               existing_comment='Controlling agency (e.g., TTN) (I-09)')
    op.alter_column('invoices', 'teif_version',
               existing_type=sa.NVARCHAR(length=10, collation='SQL_Latin1_General_CP1_CI_AS'),
               server_default=sa.text("('1.8.8')"),
               nullable=True,
               comment=None,
               existing_comment='TEIF standard version (I-08)')
    op.add_column('invoice_taxes', sa.Column('currency_code_list', sa.NVARCHAR(length=20, collation='SQL_Latin1_General_CP1_CI_AS'), server_default=sa.text("('ISO_4217')"), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_invoice_taxes_invoice_id'), table_name='invoice_taxes')
    op.create_index(op.f('IX_invoice_taxes_invoice'), 'invoice_taxes', ['invoice_id'], unique=False)
    op.alter_column('invoice_taxes', 'created_at',
               existing_type=sa.DateTime(),
               server_default=sa.text('(getdate())'),
               type_=mssql.DATETIME2(),
               nullable=True)
    op.alter_column('invoice_taxes', 'tax_amount',
               existing_type=sa.DECIMAL(precision=15, scale=3),
               comment=None,
               existing_comment='Calculated tax amount',
               existing_nullable=False)
    op.alter_column('invoice_taxes', 'taxable_amount',
               existing_type=sa.DECIMAL(precision=15, scale=3),
               comment=None,
               existing_comment='Taxable base amount',
               existing_nullable=False)
    op.alter_column('invoice_taxes', 'tax_rate',
               existing_type=sa.DECIMAL(precision=5, scale=2),
               comment=None,
               existing_comment='Tax rate as a percentage (e.g., 19.0 for 19%)',
               existing_nullable=False)
    op.alter_column('invoice_taxes', 'tax_category',
               existing_type=sa.NVARCHAR(length=10, collation='SQL_Latin1_General_CP1_CI_AS'),
               comment=None,
               existing_comment="Tax category (e.g., 'S' for Standard, 'E' for Exempt)",
               existing_nullable=True)
    op.alter_column('invoice_taxes', 'tax_type',
               existing_type=sa.NVARCHAR(length=50, collation='SQL_Latin1_General_CP1_CI_AS'),
               comment=None,
               existing_comment="Type of tax (e.g., 'TVA', 'Droit de timbre')",
               existing_nullable=False)
    op.alter_column('invoice_taxes', 'tax_code',
               existing_type=sa.NVARCHAR(length=10, collation='SQL_Latin1_General_CP1_CI_AS'),
               comment=None,
               existing_comment="Tax code (e.g., 'I-1602' for VAT, 'I-1601' for Stamp Duty)",
               existing_nullable=False)
    op.alter_column('invoice_taxes', 'invoice_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Reference to the invoice',
               existing_nullable=False)
    op.drop_index(op.f('ix_invoice_signatures_signature_status'), table_name='invoice_signatures')
    op.drop_index(op.f('ix_invoice_signatures_invoice_id'), table_name='invoice_signatures')
    op.create_index(op.f('IX_signatures_status'), 'invoice_signatures', ['signature_status'], unique=False)
    op.create_index(op.f('IX_signatures_invoice'), 'invoice_signatures', ['invoice_id'], unique=False)
    op.alter_column('invoice_signatures', 'created_at',
               existing_type=sa.DateTime(),
               server_default=sa.text('(getdate())'),
               type_=mssql.DATETIME2(),
               nullable=True)
    op.alter_column('invoice_signatures', 'verification_result',
               existing_type=sa.NVARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'),
               comment=None,
               existing_comment='Detailed result of the signature verification',
               existing_nullable=True)
    op.alter_column('invoice_signatures', 'verification_date',
               existing_type=sa.DateTime(),
               type_=mssql.DATETIME2(),
               comment=None,
               existing_comment='When the signature was last verified',
               existing_nullable=True)
    op.alter_column('invoice_signatures', 'signature_status',
               existing_type=sa.NVARCHAR(length=50, collation='SQL_Latin1_General_CP1_CI_AS'),
               server_default=sa.text("('pending')"),
               nullable=True,
               comment=None,
               existing_comment="Signature status: 'pending', 'signed', 'verified', or 'invalid'")
    op.alter_column('invoice_signatures', 'signature_value',
               existing_type=sa.NVARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'),
               comment=None,
               existing_comment='Computed signature value',
               existing_nullable=True)
    op.alter_column('invoice_signatures', 'signing_time',
               existing_type=sa.DateTime(),
               type_=mssql.DATETIME2(),
               comment=None,
               existing_comment='Timestamp when the signature was created (ISO format)',
               existing_nullable=True)
    op.alter_column('invoice_signatures', 'key_password',
               existing_type=sa.NVARCHAR(length=255, collation='SQL_Latin1_General_CP1_CI_AS'),
               comment=None,
               existing_comment='Key password (encrypted)',
               existing_nullable=True)
    op.alter_column('invoice_signatures', 'private_key_data',
               existing_type=sa.NVARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'),
               comment=None,
               existing_comment='Private key data (for testing only)',
               existing_nullable=True)
    op.alter_column('invoice_signatures', 'x509_certificate',
               existing_type=sa.NVARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'),
               comment=None,
               existing_comment='X.509 certificate in base64 format',
               existing_nullable=True)
    op.alter_column('invoice_signatures', 'signer_name',
               existing_type=sa.NVARCHAR(length=255, collation='SQL_Latin1_General_CP1_CI_AS'),
               comment=None,
               existing_comment='Name of the signer',
               existing_nullable=True)
    op.alter_column('invoice_signatures', 'signer_role',
               existing_type=sa.NVARCHAR(length=50, collation='SQL_Latin1_General_CP1_CI_AS'),
               comment=None,
               existing_comment="Role of the signer (e.g., 'Fournisseur')",
               existing_nullable=True)
    op.alter_column('invoice_signatures', 'signature_id',
               existing_type=sa.NVARCHAR(length=50, collation='SQL_Latin1_General_CP1_CI_AS'),
               comment=None,
               existing_comment='Unique identifier for the signature',
               existing_nullable=False)
    op.alter_column('invoice_signatures', 'invoice_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Reference to the signed invoice',
               existing_nullable=False)
    op.drop_column('invoice_signatures', 'updated_at')
    op.add_column('invoice_references', sa.Column('reference_value', sa.NVARCHAR(length=100, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=False))
    op.drop_table_comment(
        'invoice_references',
        existing_comment='Invoice references and identifiers',
        schema=None
    )
    op.drop_index('idx_invoice_ref_type', table_name='invoice_references')
    op.alter_column('invoice_references', 'created_at',
               existing_type=sa.DateTime(),
               server_default=sa.text('(getdate())'),
               type_=mssql.DATETIME2(),
               nullable=True)
    op.alter_column('invoice_references', 'description',
               existing_type=sa.NVARCHAR(length=255, collation='SQL_Latin1_General_CP1_CI_AS'),
               comment=None,
               existing_comment='Optional description of the reference',
               existing_nullable=True)
    op.alter_column('invoice_references', 'reference_number',
               existing_type=sa.VARCHAR(length=100, collation='SQL_Latin1_General_CP1_CI_AS'),
               server_default=sa.text("('')"),
               existing_comment='Reference number or identifier',
               existing_nullable=False)
    op.alter_column('invoice_references', 'reference_type',
               existing_type=sa.NVARCHAR(length=10, collation='SQL_Latin1_General_CP1_CI_AS'),
               comment=None,
               existing_comment="Reference type code (e.g., 'I-04' for Purchase Order, 'I-05' for Contract)",
               existing_nullable=False)
    op.alter_column('invoice_references', 'invoice_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Reference to the parent invoice',
               existing_nullable=False)
    op.drop_index(op.f('ix_invoice_monetary_amounts_invoice_id'), table_name='invoice_monetary_amounts')
    op.alter_column('invoice_monetary_amounts', 'created_at',
               existing_type=sa.DateTime(),
               server_default=sa.text('(getdate())'),
               type_=mssql.DATETIME2(),
               nullable=True)
    op.alter_column('invoice_monetary_amounts', 'currency_code_list',
               existing_type=sa.NVARCHAR(length=20, collation='SQL_Latin1_General_CP1_CI_AS'),
               server_default=sa.text("('ISO_4217')"),
               nullable=True,
               comment=None,
               existing_comment='Currency code list identifier')
    op.alter_column('invoice_monetary_amounts', 'currency',
               existing_type=sa.NVARCHAR(length=3, collation='SQL_Latin1_General_CP1_CI_AS'),
               server_default=sa.text("('TND')"),
               nullable=True,
               comment=None,
               existing_comment='Currency code (ISO 4217)')
    op.alter_column('invoice_monetary_amounts', 'description',
               existing_type=sa.NVARCHAR(length=255, collation='SQL_Latin1_General_CP1_CI_AS'),
               comment=None,
               existing_comment="Description of the amount (e.g., 'Total hors taxes')",
               existing_nullable=True)
    op.alter_column('invoice_monetary_amounts', 'amount',
               existing_type=sa.DECIMAL(precision=15, scale=3),
               comment=None,
               existing_comment='Monetary amount',
               existing_nullable=False)
    op.alter_column('invoice_monetary_amounts', 'amount_type_code',
               existing_type=sa.NVARCHAR(length=10, collation='SQL_Latin1_General_CP1_CI_AS'),
               comment=None,
               existing_comment="Type code (e.g., 'I-181' for Tax Amount, 'I-182' for Taxable Amount)",
               existing_nullable=False)
    op.alter_column('invoice_monetary_amounts', 'invoice_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Reference to the invoice',
               existing_nullable=False)
    op.add_column('invoice_lines', sa.Column('currency_code_list', sa.NVARCHAR(length=20, collation='SQL_Latin1_General_CP1_CI_AS'), server_default=sa.text("('ISO_4217')"), autoincrement=False, nullable=True))
    op.add_column('invoice_lines', sa.Column('updated_at', sa.DATETIME(), server_default=sa.text('(getdate())'), autoincrement=False, nullable=True))
    op.drop_table_comment(
        'invoice_lines',
        existing_comment='Invoice line items with TEIF 1.8.8 compliance',
        schema=None
    )
    op.drop_index(op.f('ix_invoice_lines_parent_line_id'), table_name='invoice_lines')
    op.drop_index(op.f('ix_invoice_lines_invoice_id'), table_name='invoice_lines')
    op.drop_index('idx_invoice_line_parent', table_name='invoice_lines')
    op.drop_index('idx_invoice_line_number', table_name='invoice_lines')
    op.create_index(op.f('IX_invoice_lines_parent'), 'invoice_lines', ['parent_line_id'], unique=False)
    op.create_index(op.f('IX_invoice_lines_invoice'), 'invoice_lines', ['invoice_id'], unique=False)
    op.alter_column('invoice_lines', 'created_at',
               existing_type=sa.DateTime(),
               server_default=sa.text('(getdate())'),
               type_=mssql.DATETIME2(),
               nullable=True)
    op.alter_column('invoice_lines', 'additional_info',
               existing_type=sa.VARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'),
               comment='Additional information in JSON format',
               existing_comment='Additional line-specific information in JSON format',
               existing_nullable=True)
    op.alter_column('invoice_lines', 'line_date',
               existing_type=sa.DATE(),
               comment=None,
               existing_comment='Date specific to this line (e.g., service date) (I-80)',
               existing_nullable=True)
    op.alter_column('invoice_lines', 'currency',
               existing_type=sa.NVARCHAR(length=3, collation='SQL_Latin1_General_CP1_CI_AS'),
               server_default=sa.text("('TND')"),
               nullable=True,
               comment=None,
               existing_comment='Currency code (ISO 4217)')
    op.alter_column('invoice_lines', 'discount_reason',
               existing_type=sa.NVARCHAR(length=255, collation='SQL_Latin1_General_CP1_CI_AS'),
               comment=None,
               existing_comment="Reason for discount (e.g., 'Special 10% discount') (I-79)",
               existing_nullable=True)
    op.alter_column('invoice_lines', 'discount_amount',
               existing_type=sa.DECIMAL(precision=15, scale=3),
               server_default=sa.text('((0))'),
               nullable=True,
               comment=None,
               existing_comment='Discount amount for this line (I-78)')
    op.alter_column('invoice_lines', 'line_total_ht',
               existing_type=sa.DECIMAL(precision=15, scale=3),
               comment=None,
               existing_comment='Line total excluding tax (quantity * unit_price) (I-77)',
               existing_nullable=False)
    op.alter_column('invoice_lines', 'unit_price',
               existing_type=sa.DECIMAL(precision=15, scale=3),
               comment=None,
               existing_comment='Unit price excluding tax (I-76)',
               existing_nullable=False)
    op.alter_column('invoice_lines', 'unit',
               existing_type=sa.NVARCHAR(length=10, collation='SQL_Latin1_General_CP1_CI_AS'),
               server_default=sa.text("('PCE')"),
               nullable=True,
               comment=None,
               existing_comment="Unit of measure (e.g., 'PCE', 'KIT') (I-75)")
    op.alter_column('invoice_lines', 'quantity',
               existing_type=sa.DECIMAL(precision=10, scale=3),
               comment=None,
               existing_comment='Item quantity (I-74)',
               existing_nullable=False)
    op.alter_column('invoice_lines', 'description',
               existing_type=sa.Text(),
               type_=sa.NVARCHAR(length=1000, collation='SQL_Latin1_General_CP1_CI_AS'),
               comment=None,
               existing_comment='Detailed item description (I-73)',
               existing_nullable=False)
    op.alter_column('invoice_lines', 'item_code',
               existing_type=sa.NVARCHAR(length=100, collation='SQL_Latin1_General_CP1_CI_AS'),
               comment=None,
               existing_comment='Item code (I-72)',
               existing_nullable=True)
    op.alter_column('invoice_lines', 'item_identifier',
               existing_type=sa.NVARCHAR(length=100, collation='SQL_Latin1_General_CP1_CI_AS'),
               comment=None,
               existing_comment="Item identifier (e.g., 'DDM-001', 'DDR-001', 'KIT-001') (I-71)",
               existing_nullable=True)
    op.alter_column('invoice_lines', 'parent_line_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Reference to parent line for sub-lines',
               existing_nullable=True)
    op.alter_column('invoice_lines', 'line_number',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Line number in the invoice (I-70)',
               existing_nullable=False)
    op.alter_column('invoice_lines', 'invoice_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Reference to the parent invoice',
               existing_nullable=False)
    op.alter_column('invoice_dates', 'created_at',
               existing_type=sa.DateTime(),
               server_default=sa.text('(getdate())'),
               type_=mssql.DATETIME2(),
               nullable=True)
    op.alter_column('invoice_dates', 'description',
               existing_type=sa.NVARCHAR(length=255, collation='SQL_Latin1_General_CP1_CI_AS'),
               comment=None,
               existing_comment='Optional description of the date',
               existing_nullable=True)
    op.alter_column('invoice_dates', 'date_format',
               existing_type=sa.NVARCHAR(length=20, collation='SQL_Latin1_General_CP1_CI_AS'),
               comment=None,
               existing_comment='Date format (ddMMyy, ddMMyy-ddMMyy, etc.)',
               existing_nullable=False)
    op.alter_column('invoice_dates', 'function_code',
               existing_type=sa.NVARCHAR(length=10, collation='SQL_Latin1_General_CP1_CI_AS'),
               comment=None,
               existing_comment='Date function code (I-31, I-32, I-36, etc.)',
               existing_nullable=False)
    op.alter_column('invoice_dates', 'date_text',
               existing_type=sa.NVARCHAR(length=50, collation='SQL_Latin1_General_CP1_CI_AS'),
               comment=None,
               existing_comment='Date in specified format (ddMMyy or ddMMyy-ddMMyy)',
               existing_nullable=False)
    op.alter_column('invoice_dates', 'invoice_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Reference to the parent invoice',
               existing_nullable=False)
    op.alter_column('generated_xml_files', 'generated_at',
               existing_type=sa.DateTime(),
               server_default=sa.text('(getdate())'),
               type_=mssql.DATETIME2(),
               nullable=True,
               comment=None,
               existing_comment='When this XML file was generated')
    op.alter_column('generated_xml_files', 'signature_validation',
               existing_type=mssql.BIT(),
               server_default=sa.text('((0))'),
               nullable=True,
               comment=None,
               existing_comment='Whether the XML signature is valid')
    op.alter_column('generated_xml_files', 'schema_validation',
               existing_type=mssql.BIT(),
               server_default=sa.text('((0))'),
               nullable=True,
               comment=None,
               existing_comment='Whether the XML passed schema validation')
    op.alter_column('generated_xml_files', 'validation_errors',
               existing_type=sa.NVARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'),
               comment=None,
               existing_comment='Any validation errors encountered',
               existing_nullable=True)
    op.alter_column('generated_xml_files', 'validation_status',
               existing_type=sa.NVARCHAR(length=50, collation='SQL_Latin1_General_CP1_CI_AS'),
               server_default=sa.text("('pending')"),
               nullable=True,
               comment=None,
               existing_comment='Current validation status')
    op.alter_column('generated_xml_files', 'xml_version',
               existing_type=sa.NVARCHAR(length=10, collation='SQL_Latin1_General_CP1_CI_AS'),
               server_default=sa.text("('1.8.8')"),
               nullable=True,
               comment=None,
               existing_comment='TEIF XML schema version')
    op.alter_column('generated_xml_files', 'file_size',
               existing_type=sa.BIGINT(),
               comment=None,
               existing_comment='Size of the XML file in bytes',
               existing_nullable=True)
    op.alter_column('generated_xml_files', 'file_path',
               existing_type=sa.NVARCHAR(length=500, collation='SQL_Latin1_General_CP1_CI_AS'),
               comment=None,
               existing_comment='Filesystem path where the XML is stored',
               existing_nullable=True)
    op.alter_column('generated_xml_files', 'xml_content',
               existing_type=sa.NVARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'),
               comment=None,
               existing_comment='The actual XML content of the invoice',
               existing_nullable=False)
    op.alter_column('generated_xml_files', 'invoice_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Reference to the source invoice',
               existing_nullable=False)
    op.drop_column('generated_xml_files', 'created_at')
    op.drop_column('generated_xml_files', 'updated_at')
    op.alter_column('contact_communications', 'created_at',
               existing_type=sa.DateTime(),
               server_default=sa.text('(getdate())'),
               type_=mssql.DATETIME2(),
               nullable=True)
    op.alter_column('contact_communications', 'communication_value',
               existing_type=sa.NVARCHAR(length=255, collation='SQL_Latin1_General_CP1_CI_AS'),
               comment=None,
               existing_comment='The communication value (e.g., phone number, email)',
               existing_nullable=False)
    op.alter_column('contact_communications', 'communication_type',
               existing_type=sa.NVARCHAR(length=10, collation='SQL_Latin1_General_CP1_CI_AS'),
               comment=None,
               existing_comment="Type of communication (e.g., 'TE' for telephone, 'EM' for email)",
               existing_nullable=False)
    op.alter_column('company_references', 'created_at',
               existing_type=sa.DateTime(),
               server_default=sa.text('(getdate())'),
               type_=mssql.DATETIME2(),
               nullable=True)
    op.alter_column('company_references', 'description',
               existing_type=sa.NVARCHAR(length=255, collation='SQL_Latin1_General_CP1_CI_AS'),
               comment=None,
               existing_comment='Optional description of the reference',
               existing_nullable=True)
    op.alter_column('company_references', 'reference_value',
               existing_type=sa.NVARCHAR(length=100, collation='SQL_Latin1_General_CP1_CI_AS'),
               comment=None,
               existing_comment='The reference value',
               existing_nullable=False)
    op.alter_column('company_references', 'reference_type',
               existing_type=sa.NVARCHAR(length=10, collation='SQL_Latin1_General_CP1_CI_AS'),
               comment=None,
               existing_comment="Reference type (e.g., 'VA' for VAT, 'FC' for Fiscal Code)",
               existing_nullable=False)
    op.alter_column('company_contacts', 'created_at',
               existing_type=sa.DateTime(),
               server_default=sa.text('(getdate())'),
               type_=mssql.DATETIME2(),
               nullable=True)
    op.alter_column('company_contacts', 'contact_identifier',
               existing_type=sa.NVARCHAR(length=50, collation='SQL_Latin1_General_CP1_CI_AS'),
               comment=None,
               existing_comment='Unique identifier for the contact',
               existing_nullable=True)
    op.alter_column('company_contacts', 'contact_name',
               existing_type=sa.NVARCHAR(length=255, collation='SQL_Latin1_General_CP1_CI_AS'),
               comment=None,
               existing_comment='Full name of the contact person',
               existing_nullable=True)
    op.alter_column('company_contacts', 'function_code',
               existing_type=sa.NVARCHAR(length=10, collation='SQL_Latin1_General_CP1_CI_AS'),
               comment=None,
               existing_comment="Contact function code (e.g., 'BU' for buyer, 'SU' for supplier)",
               existing_nullable=True)
    op.drop_table_comment(
        'companies',
        existing_comment='Companies and organizations that are suppliers or customers in the system',
        schema=None
    )
    op.drop_index(op.f('ix_companies_vat_number'), table_name='companies')
    op.drop_index(op.f('ix_companies_identifier'), table_name='companies')
    op.drop_index('idx_company_vat', table_name='companies')
    op.drop_index('idx_company_tax_id', table_name='companies')
    op.drop_index('idx_company_name_city', table_name='companies')
    op.drop_index('idx_company_identifier', table_name='companies')
    op.drop_index('idx_company_commercial_register', table_name='companies')
    op.create_index(op.f('IX_companies_vat_number'), 'companies', ['vat_number'], unique=False)
    op.create_index(op.f('IX_companies_identifier'), 'companies', ['identifier'], unique=False)
    op.alter_column('companies', 'created_at',
               existing_type=sa.DateTime(),
               server_default=sa.text('(getdate())'),
               type_=mssql.DATETIME2(),
               nullable=True)
    op.alter_column('companies', 'updated_at',
               existing_type=sa.DATETIME(),
               server_default=sa.text('(getdate())'),
               existing_nullable=True)
    op.alter_column('companies', 'additional_info',
               existing_type=sa.VARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'),
               comment='Additional company information in JSON format',
               existing_comment='Additional TEIF-specific information in JSON format',
               existing_nullable=True)
    op.alter_column('companies', 'website',
               existing_type=sa.NVARCHAR(length=255, collation='SQL_Latin1_General_CP1_CI_AS'),
               comment=None,
               existing_comment='Company website URL (I-104 in TEIF)',
               existing_nullable=True)
    op.alter_column('companies', 'fax',
               existing_type=sa.NVARCHAR(length=50, collation='SQL_Latin1_General_CP1_CI_AS'),
               comment=None,
               existing_comment='Fax number (I-118 in TEIF)',
               existing_nullable=True)
    op.alter_column('companies', 'email',
               existing_type=sa.NVARCHAR(length=255, collation='SQL_Latin1_General_CP1_CI_AS'),
               comment=None,
               existing_comment='Primary email address (I-102 in TEIF)',
               existing_nullable=True)
    op.alter_column('companies', 'phone',
               existing_type=sa.NVARCHAR(length=50, collation='SQL_Latin1_General_CP1_CI_AS'),
               comment=None,
               existing_comment='Primary phone number (I-101 in TEIF)',
               existing_nullable=True)
    op.alter_column('companies', 'address_language',
               existing_type=sa.NVARCHAR(length=2, collation='SQL_Latin1_General_CP1_CI_AS'),
               server_default=sa.text("('FR')"),
               nullable=True,
               comment=None,
               existing_comment='Language code for address (lang attribute in TEIF)')
    op.alter_column('companies', 'address_country_code',
               existing_type=sa.String(length=2),
               server_default=sa.text("('TN')"),
               type_=sa.NVARCHAR(length=3, collation='SQL_Latin1_General_CP1_CI_AS'),
               nullable=True,
               comment=None,
               existing_comment='ISO 3166-1 alpha-2 country code (Country in TEIF)')
    op.alter_column('companies', 'address_postal_code',
               existing_type=sa.NVARCHAR(length=20, collation='SQL_Latin1_General_CP1_CI_AS'),
               comment=None,
               existing_comment='Postal/ZIP code (PostalCode in TEIF)',
               existing_nullable=True)
    op.alter_column('companies', 'address_city',
               existing_type=sa.NVARCHAR(length=100, collation='SQL_Latin1_General_CP1_CI_AS'),
               comment=None,
               existing_comment='City name (CityName in TEIF)',
               existing_nullable=True)
    op.alter_column('companies', 'address_street',
               existing_type=sa.NVARCHAR(length=500, collation='SQL_Latin1_General_CP1_CI_AS'),
               comment=None,
               existing_comment='Street address (Street in TEIF)',
               existing_nullable=True)
    op.alter_column('companies', 'commercial_register',
               existing_type=sa.NVARCHAR(length=50, collation='SQL_Latin1_General_CP1_CI_AS'),
               comment=None,
               existing_comment='Commercial register number (I-815 in TEIF)',
               existing_nullable=True)
    op.alter_column('companies', 'tax_id',
               existing_type=sa.NVARCHAR(length=50, collation='SQL_Latin1_General_CP1_CI_AS'),
               comment=None,
               existing_comment='Tax identification number (I-01 in TEIF)',
               existing_nullable=True)
    op.alter_column('companies', 'vat_number',
               existing_type=sa.NVARCHAR(length=50, collation='SQL_Latin1_General_CP1_CI_AS'),
               comment=None,
               existing_comment='VAT registration number (I-1602 in TEIF)',
               existing_nullable=False)
    op.alter_column('companies', 'name',
               existing_type=sa.NVARCHAR(length=255, collation='SQL_Latin1_General_CP1_CI_AS'),
               comment=None,
               existing_comment='Company name (PartnerName in TEIF)',
               existing_nullable=False)
    op.alter_column('companies', 'identifier',
               existing_type=sa.NVARCHAR(length=50, collation='SQL_Latin1_General_CP1_CI_AS'),
               comment=None,
               existing_comment='Unique company identifier (I-01 for TEIF)',
               existing_nullable=False)
    op.add_column('additional_documents', sa.Column('file_path', sa.NVARCHAR(length=500, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True))
    op.add_column('additional_documents', sa.Column('updated_at', sa.DATETIME(), autoincrement=False, nullable=False))
    op.add_column('additional_documents', sa.Column('document_id', sa.NVARCHAR(length=100, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=False))
    op.add_column('additional_documents', sa.Column('document_name', sa.NVARCHAR(length=255, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True))
    op.drop_table_comment(
        'additional_documents',
        existing_comment='Additional documents related to invoices',
        schema=None
    )
    op.drop_index('idx_document_type', table_name='additional_documents')
    op.alter_column('additional_documents', 'created_at',
               existing_type=sa.DATETIME(),
               server_default=sa.text('(getdate())'),
               existing_nullable=False)
    op.alter_column('additional_documents', 'description',
               existing_type=sa.NVARCHAR(length=500, collation='SQL_Latin1_General_CP1_CI_AS'),
               comment=None,
               existing_comment='Document description',
               existing_nullable=True)
    op.alter_column('additional_documents', 'document_date',
               existing_type=sa.DATE(),
               comment=None,
               existing_comment='Document date',
               existing_nullable=True)
    op.alter_column('additional_documents', 'document_number',
               existing_type=sa.VARCHAR(length=100, collation='SQL_Latin1_General_CP1_CI_AS'),
               server_default=sa.text("('')"),
               existing_comment='Document number or identifier',
               existing_nullable=False)
    op.alter_column('additional_documents', 'document_type',
               existing_type=sa.NVARCHAR(length=10, collation='SQL_Latin1_General_CP1_CI_AS'),
               nullable=True,
               comment=None,
               existing_comment="Document type code (e.g., 'I-11' for Invoice, 'I-12' for Credit Note)")
    op.alter_column('additional_documents', 'invoice_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Reference to the parent invoice',
               existing_nullable=False)
    # ### end Alembic commands ###

# Indication pour Alembic que la migration est transactionnelle
# et peut être exécutée dans une transaction
# Cela est particulièrement important pour SQL Server
transactional = True
